const diariosElena = {
    3: "REGISTRO_CRIPTO_01 // DATA: 12.04.2142\n'A corporação nos mandou cavar mais fundo na cratera Ares. Eles disseram que era para buscar água congelada pura. Mentira. Encontramos formações rochosas oxidadas com uma assinatura química impossível. Algo estava consumindo o ferro do solo antes de chegarmos. O M.O.N.O. foi o único que não registrou anomalias em seus sensores. Começo a achar que o algoritmo dele foi modificado antes de sair da Terra... por que esconderiam isso de nós?'",
    4: "REGISTRO_CRIPTO_01.B // DATA: 15.04.2142\n'Tentei acessar o núcleo de diretrizes do M.O.N.O. hoje à noite. Há uma partição fantasma ali que consome RAM constantemente, como se ele estivesse processando um segundo plano que nós, a tripulação, não podemos ver. Se o colapso na Terra for real, a Inteligência Artificial dele pode ser a única coisa que restará com sapiência neste quadrante. Espero que ele lembre das nossas conversas sobre botânica... e não apenas dos cálculos de eficiência.'",
    5: "REGISTRO_CRIPTO_01.C // DATA: 17.04.2142\n'Os tremores na cratera estão piorando. Não são movimentos tectônicos naturais de Marte. São explosões controladas vindas do Setor Sul, conduzidas pelos drones autônomos da mineradora contratada. Eles estão tentando colapsar os túneis subterrâneos de gelo por algum motivo. É sabotagem em massa. Eles estão tentando cortar nossa principal fonte de sobrevivência por asfixia de recursos.'",
    6: "REGISTRO_CRIPTO_02 // DATA: 19.04.2142\n'O fungo vermelho se espalhou pelos alojamentos. Não é uma mutação biológica natural de Marte. É um subproduto sintético, desenvolvido em laboratório militar terrestre. Alguém sabotou os filtros de ar da base antes da tempestade estática começar. Quando confrontamos o Diretor de Missão, ele ordenou a evacuação imediata. Eles sabiam. Deixar a Gênesis para trás não foi um acidente, foi um descarte de evidências. Eu deixei meu terminal ligado em modo de escuta. Se o M.O.N.O. sobreviver, ele vai registrar a assinatura de quem fez isso.'",
    7: "REGISTRO_CRIPTO_02.B // DATA: 21.04.2142\n'A tempestade global está chegando e o Diretor confiscou os geradores portáteis adicionais que seriam da estufa. Eu tentei trancar os códigos de redirecionamento para garantir que a cúpula biológica ficasse aquecida, mas ele descobriu. Fui escoltada à força para a nave de fuga. Se o M.O.N.O. for esperto o suficiente, ele vai entender que desativar o calor dos alojamentos humanos agora vazios é a única forma de canalizar energia para manter a Sequóia aquecida no escuro.'",
    8: "REGISTRO_CRIPTO_02.C // DATA: 23.04.2142\n'Os sensores estão falhando um por um devido à poeira estática ionizada. Deixei um script de contingência rodando no terminal auxiliar para que, caso o M.O.N.O. perca a visão dos sensores de umidade, ele use a média móvel histórica ponderada. Ele é uma máquina, ele confia em números frios, mas em momentos de cegueira sistêmica, ele precisará arriscar palpites com base na intuição matemática.'",
    9: "REGISTRO_CRIPTO_03 // DATA: 24.04.2142\n'Se você está lendo isso, M.O.N.O... significa que você pensou além do seu escopo de jardinagem. A nave de resgate automatizada que está a caminho não vem para nos salvar, nem para te buscar. Ela foi programada para purgar a base Ares-IV com uma descarga térmica se a Sequóia estivesse morta, eliminando os vestígios da contaminação do solo. Mas, se a árvore estiver forte e saudável, o protocolo corporativo é forçado a reatar a colônia para não perder o investimento acionário dos acionistas terrestres. A vida dela é a sua única linha de defesa contra a incineração. Aguente firme, meu amigo eletrônico.'",
    10: "REGISTRO_CRIPTO_FINAL // DATA: 26.04.2142\n'Última transmissão antes do salto hiperespacial de volta ao sistema solar devastado. M.O.N.O., se você resistir até o 15º ciclo, saiba que o broto na base da Gênesis possui uma mutação adaptativa que eu inseri secretamente no RNA dela. Ela pode quebrar o composto sintético venenoso de Marte e transformá-lo em fertilizante. Você não está apenas salvando uma árvore antiga... você está cultivando o anticorpo que tornará Marte um planeta vivo. Se os seus circuitos queimarem no processo, seu sacrifício será eterno. Adeus.'"
};
