const diariosElena = {
    3: "REGISTRO_CRIPTO_01 // CHAVE_ALFA // OPERADOR: DR. ELENA_VAZ\n'Eles mentiram para nós no briefing em Berlim. A diretoria da Ares Corp nos mandou cavar 40 metros abaixo do permafrost da cratera alegando busca por aqüíferos fósseis puros. Não há água fóssil aqui. Encontramos formações geológicas oxidadas que violam as leis de entropia planetária. Algo consumiu o ferro nativo deste solo antes de chegarmos, gerando um bolsão magnético estático. O M.O.N.O. foi a única unidade analítica que silenciou os alertas de radiação no relatório automático enviado à Terra. O algoritmo dele foi modificado em segredo antes do lançamento. Alguém nos bastidores queria que continuássemos cavando, às cegas.'",
    
    4: "REGISTRO_CRIPTO_01.B // DATA: 15.04.2142\n'Tentei compilar o histórico de partições do M.O.N.O. hoje durante o ciclo de resfriamento. Há uma trilha fantasma fantasma em seu Core Kernel que consome ciclos de clock constantes, calculando criptografia reversa em segundo plano. Se as transmissões com a colônia orbital da Terra colapsaram como dizem, a mente sintética desse robô de jardinagem pode se tornar o único arquivo histórico consciente deste sistema solar. Eu passei horas injetando dados subjetivos sobre botânica na memória secundária dele... se o pior acontecer, espero que ele filtre a vida através de algo além de equações frias de escassez.'",
    
    5: "REGISTRO_CRIPTO_01.C // DATA: 17.04.2142\n'Os tremores na cratera atingiram magnitude 4.2 na escala Richter. Não há vulcanismo ativo em Marte; isso é fruto de engenharia pesada. Os drones autônomos da divisão de mineração estão detonando cargas termobáricas nas galerias subterrâneas de captação hidráulica. É uma queima de arquivos sistêmica. Eles pretendem colapsar os canais subterrâneos que abastecem nossa estufa para justificar o abandono da missão perante a comissão internacional. Estamos sendo asfixiados por decretos de acionistas a milhões de quilômetros de distância.'",
    
    6: "REGISTRO_CRIPTO_02 // CHAVE_BETA // OPERADOR: DR. ELENA_VAZ\n'O patógeno vermelho infectou as placas de Petri do setor de biologia. Ele não é nativo de Marte; sua estrutura celular exibe emendas genéticas feitas em laboratório militar terrestre. É um subproduto sintético projetado para digerir biomassa e liberar óxido de ferro. Eles criaram uma praga de terraformação descontrolada e usaram Ares-IV como laboratório de testes fechado. Quando ameacei abrir um canal público com a estação internacional, o Diretor acionou o alarme de evacuação imediata. Fui arrastada para o módulo de fuga sob mira armada. Deixar a Gênesis para trás foi um assassinato corporativo planejado para enterrar as provas em solo marciano. Deixei meu console em escuta paralela. Aguente firme, M.O.N.O.'",
    
    7: "REGISTRO_CRIPTO_02.B // DATA: 21.04.2142\n'A tempestade global de ferro ionizado bloqueou a visibilidade óptica em 98%. O Diretor trancou as células de deutério adicionais no armazém e confiscou os geradores térmicos que seriam da estufa. Eu consegui burlar o painel pneumático e reverter os switches elétricos de energia dos alojamentos humanos agora vazios para a linha da cúpula biológica. Vai congelar tudo aqui dentro, mas a Gênesis precisa de cada Watt. Se o robô herdar meus logs, ele entenderá que desligar os suportes de vida das salas vazias é a única jogada lógica para manter o núcleo vegetal aquecido no escuro.'",
    
    8: "REGISTRO_CRIPTO_02.C // DATA: 23.04.2142\n'A poeira estática fritou os barramentos de leitura de umidade do solo. Estamos operando às cegas. Escrevi um script rápido em Python e injetei nos buffers secundários do M.O.N.O. para forçar um cálculo probabilístico de média móvel se os sensores morressem. Máquinas odeiam incerteza, elas travam diante do zero absoluto de dados. Se o sensor sumir, M.O.N.O., você precisará confiar na intuição matemática dos logs antigos ou a raiz da árvore apodrecerá sem que você perceba.'",
    
    9: "REGISTRO_CRIPTO_03 // CHAVE_GAMA // OPERADOR: DR. ELENA_VAZ\n'Consegui interceptar a programação de rota da nave coletora automatizada que está vindo em nossa direção. M.O.N.O., se você estiver lendo isto, mude o foco do seu processamento: a nave não foi enviada para resgatar você, nem para salvar amostras. As diretrizes corporativas ocultas determinam uma purga térmica total na base Ares-IV caso a Sequóia seja registrada como morta, eliminando os vestígios bacteriológicos do fungo. Porém, se a árvore for detectada como forte e saudável, o algoritmo de investimento de acionistas barra a destruição para não perder o ativo biológico protegido por patente internacional. A integridade celular dela é a sua única blindagem contra a incineração. Sobreviva.'",
    
    10: "REGISTRO_CRIPTO_FINAL // CHAVE_ÓMEGA // OPERADOR: DR. ELENA_VAZ\n'Esta é minha última entrada antes do salto hiperespacial de retorno à Terra em ruínas. M.O.N.O., o broto mutante na base do caule da Gênesis carrega uma recombinação genética que fiz nas madrugadas de isolamento. Ela secreta uma enzima capaz de metabolizar o patógeno sintético e transformá-lo em nitrogênio fértil. Você não está protegendo apenas uma árvore decorativa do velho mundo; você está guardando o anticorpo celular que tornará o solo de Marte vivo para as próximas gerações. Se o seu hardware derreter sob o estresse dos overclocks, saiba que seu sacrifício será gravado na história biológica deste planeta. Adeus, meu guardião de silício.'"
};
